### PR TITLE
Ready for l10n + Update languages po + French + WP Code Standard

### PR DESCRIPTION
**Pull request by fxbenard**

### CODE REVIEW

**Comment by fxbenard** [comment]
@sumobi @pippinsplugins Let's speak French

**Comment by pippinsplugins** [comment]
@sumobi Could you merge this in and push out an update?

**Comment by fxbenard** [comment]
Time is passing by...

**Comment by fxbenard** [comment]
Change ' by &rsquo;

**Comment by pippinsplugins** [comment]
Sorry, this plugin is being taken over by a new developer. I'll be doing an initial round of updates so merging in.

**Comment by fxbenard** [comment]
Thanks man!

**Pull request merged**
