### PR TITLE
Version 1.3

### PR DESCRIPTION
**Pull request by pippinsplugins**
Simplify entire code base for improved reliability, extension compatibility, and clarify.

### CODE REVIEW

**Comment by pippinsplugins** [comment]
Resolves #1, #14, #12, #9, #8, #6, #5, #3

**Comment by pippinsplugins** [comment]
@sumobi @mindctrl @SDavisMedia any of you able to test this soon? I'd like to get it deployed

**Comment by sumobi** [comment]
@pippinsplugins oh awesome, absolutely :+1:

**Comment by sumobi** [comment]
@pippinsplugins @mindctrl @SDavisMedia 

Unless anyone else wants to test this I'm happy to release the update. Thanks for this @pippinsplugins

**Comment by pippinsplugins** [comment]
Woot! Full steam ahead @sumobi

**Pull request merged**
